apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-worker
  namespace: rabbitmq-demo
  labels:
    app: rabbitmq-worker
    app.kubernetes.io/part-of: machine-identity-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rabbitmq-worker
  template:
    metadata:
      labels:
        app: rabbitmq-worker
    spec:
      containers:
      - name: worker
        image: 10.42.0.88:5000/rabbitmq-worker:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: RABBITMQ_URL
          value: "amqp://admin:rabbitmq-admin-password-change-me@rabbitmq.rabbitmq.svc:5672/"
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
