apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: pki
    app.kubernetes.io/part-of: machine-identity-platform
    gitops.maturity: advanced
spec:
  project: default
  source:
    repoURL: https://github.com/AdamKnight02/homelab-gitops.git
    targetRevision: main
    path: apps/pki
  destination:
    server: https://kubernetes.default.svc
    namespace: pki
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: batch
      kind: CronJob
      jsonPointers:
        - /spec/suspend
  revisionHistoryLimit: 10
