apiVersion: v1
kind: ServiceAccount
metadata:
  name: spire-cert-api
  namespace: pki
  labels:
    app.kubernetes.io/part-of: machine-identity-platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spire-cert-worker
  namespace: pki
  labels:
    app.kubernetes.io/part-of: machine-identity-platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spire-ca-service
  namespace: pki
  labels:
    app.kubernetes.io/part-of: machine-identity-platform
