apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: rabbitmq
  labels:
    app: rabbitmq
    app.kubernetes.io/part-of: machine-identity-platform
type: Opaque
stringData:
  password: "rabbitmq-admin-password-change-me"
