apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: openbao
  namespace: argocd

spec:
  project: default

  sources:
    - repoURL: https://openbao.github.io/openbao-helm
      chart: openbao
      targetRevision: 0.29.2
      helm:
        releaseName: openbao
        valueFiles:
          - $values/apps/openbao/values.yaml

    - repoURL: https://github.com/AdamKnight02/homelab-gitops.git
      targetRevision: main
      ref: values

    - repoURL: https://github.com/AdamKnight02/homelab-gitops.git
      targetRevision: main
      path: apps/openbao/resources

  destination:
    server: https://kubernetes.default.svc
    namespace: openbao

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
