apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openbao

resources:
  - networkpolicy-allow-pki.yaml
  - resources/policy-pki-workloads.hcl
  - resources/role-pki-workloads.yaml
  - resources/kubernetes-auth-pki.yaml
