apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spire

resources:
  - namespace.yaml
  - configmap-server.yaml
  - configmap-agent.yaml
  - configmap-bundle.yaml
  - serviceaccount-server.yaml
  - serviceaccount-agent.yaml
  - clusterrole-server.yaml
  - clusterrole-agent.yaml
  - clusterrolebinding-server.yaml
  - clusterrolebinding-agent.yaml
  - service.yaml
  - statefulset-server.yaml
  - daemonset-agent.yaml
  - networkpolicy-server.yaml
  - networkpolicy-agent.yaml
